// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mohamed Fsili (https://sketchfab.com/medraphc)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-flying-island-49c22c7d4f3249688a000fc526b84a76
Title: Low Poly Flying Island
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/model/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.5}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0.384, 1.761, 2.286]}
            rotation={[0.462, -0.035, 0.37]}
            scale={0.102}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_9.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials["Material.005"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_11.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group
            position={[7.074, 2.168, 0.819]}
            rotation={[0.279, -0.914, 0.352]}
            scale={0.036}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_13.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_14.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[-4.593, 2.095, 1.683]}
            rotation={[0, 0.617, 0]}
            scale={[0.393, 0.252, 0.393]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_16.geometry}
              material={materials.Material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_17.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_18.geometry}
              material={materials["Material.008"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_19.geometry}
              material={materials["Material.009"]}
            />
          </group>
          <group
            position={[1.163, 1.413, 5.186]}
            rotation={[0.245, 0.496, 0.222]}
            scale={0.124}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_21.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_22.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_23.geometry}
              material={materials["Material.005"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_24.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group
            position={[1.148, 1.302, 4.522]}
            rotation={[3.123, 1.188, 3.095]}
            scale={0.067}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_26.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_27.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_28.geometry}
              material={materials["Material.005"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_29.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group
            position={[6.207, 1.932, -1.136]}
            rotation={[0.335, -0.454, 0.089]}
            scale={0.037}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_31.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_32.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[6.737, 1.978, -0.388]}
            rotation={[0, 0, 0.393]}
            scale={0.065}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_34.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_35.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[7.466, 2.267, 0.142]}
            rotation={[-0.014, -0.112, -0.041]}
            scale={0.076}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_37.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_38.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[5.975, 1.626, 0.204]}
            rotation={[-2.831, 0.357, 2.764]}
            scale={0.03}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_40.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_41.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[-0.023, 1.663, -4.536]}
            rotation={[1.91, 1.433, -1.626]}
            scale={0.086}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_43.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_44.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_45.geometry}
              material={materials["Material.005"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_46.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group
            position={[-1.109, 1.611, -2.798]}
            rotation={[2.582, 1.377, -2.419]}
            scale={0.067}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_48.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_49.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_50.geometry}
              material={materials["Material.005"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_51.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group
            position={[-0.358, 1.467, -3.12]}
            rotation={[3.116, -0.404, -2.85]}
            scale={0.117}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_53.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_54.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_55.geometry}
              material={materials["Material.005"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_56.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group
            position={[-5.644, 1.851, 0.236]}
            rotation={[0.196, 0.677, -0.162]}
            scale={0.061}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_58.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_59.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[0.433, 2.511, 7.945]}
            rotation={[-0.045, 0.104, 0.268]}
            scale={0.065}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_61.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_62.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[-2.304, 1.573, -3.775]}
            rotation={[2.993, 0.565, -2.923]}
            scale={0.057}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_64.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_65.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_66.geometry}
              material={materials["Material.005"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_67.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group
            position={[-6.146, 2.022, 0.313]}
            rotation={[0.05, 0.259, -0.111]}
            scale={0.025}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_69.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_70.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[-5.175, 1.702, 0.685]}
            rotation={[0.091, -0.422, 0.121]}
            scale={0.043}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_72.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_73.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[-0.312, 1.963, 2.095]}
            rotation={[0.157, -0.176, -0.099]}
            scale={0.036}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_75.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_76.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[-0.727, 2.429, 1.075]}
            rotation={[0.128, -0.085, -0.073]}
            scale={0.034}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_78.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_79.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[0.288, 2.059, 1.117]}
            rotation={[2.568, 0.97, -2.459]}
            scale={0.095}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_81.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_82.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_83.geometry}
              material={materials["Material.005"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_84.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group
            position={[4.44, 1.601, -5.007]}
            rotation={[0.095, 1.232, 0.086]}
            scale={0.065}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_96.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_97.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[4.106, 2.753, -6.131]}
            rotation={[-2.974, 1.365, -3.014]}
            scale={0.065}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_99.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_100.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[4.533, 2.576, -5.761]}
            rotation={[-0.066, 1.291, 0.226]}
            scale={0.045}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_102.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_103.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[4.915, 2.845, -5.915]}
            rotation={[-0.241, -0.731, -0.128]}
            scale={0.032}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_105.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_106.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[-0.11, 2.255, 8.063]}
            rotation={[-0.045, 0.104, 0.268]}
            scale={0.036}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_108.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_109.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[0.104, 2.029, 8.681]}
            rotation={[-2.5, 0.699, 2.633]}
            scale={0.061}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_111.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_112.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[6.461, 1.893, 0.886]}
            rotation={[2.946, 0.618, -3.105]}
            scale={0.069}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_114.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_115.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_116.geometry}
              material={materials["Material.005"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_117.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials["Material.003"]}
            scale={10}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials["Material.001"]}
            position={[-0.014, 1.446, -0.024]}
            rotation={[0, -0.637, 0]}
            scale={10.097}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_86.geometry}
            material={materials.material_0}
            position={[-6.824, 6.284, -4.472]}
            rotation={[0, -0.019, 0]}
            scale={0.72}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_88.geometry}
            material={materials.cloud}
            position={[-6.311, 5.038, -3.602]}
            rotation={[-0.393, -0.003, -0.078]}
            scale={0.534}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_90.geometry}
            material={materials.cloud}
            position={[6.597, 6.268, 0.85]}
            rotation={[0.881, 0.076, 0.417]}
            scale={0.876}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_92.geometry}
            material={materials.material_0}
            position={[3.228, 5.228, -5.024]}
            rotation={[-1.935, 0.598, -0.271]}
            scale={[0.759, 0.759, 0.894]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_94.geometry}
            material={materials.material_0}
            position={[7.467, 4.743, 4.554]}
            rotation={[3.084, -0.011, -3.076]}
            scale={0.599}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_119.geometry}
            material={materials.cloud}
            position={[5.786, 5.102, 0.83]}
            rotation={[0.799, -0.43, 0.686]}
            scale={0.414}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_121.geometry}
            material={materials.cloud}
            position={[6.729, 5.224, 1.486]}
            rotation={[0.039, 0.131, 0.082]}
            scale={0.238}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_123.geometry}
            material={materials["Material.004"]}
            position={[3.999, -3.067, 6.577]}
            rotation={[2.674, -0.429, 1.297]}
            scale={0.334}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_125.geometry}
            material={materials["Material.004"]}
            position={[3.36, -2.696, 7.036]}
            rotation={[1.304, -0.645, -0.769]}
            scale={0.288}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_127.geometry}
            material={materials["Material.004"]}
            position={[3.398, -3.437, 6.619]}
            rotation={[1.133, 0.389, -2.124]}
            scale={0.414}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_129.geometry}
            material={materials["Material.006"]}
            position={[2.655, 2.073, -4.707]}
            rotation={[-0.369, 0.432, 0.544]}
            scale={0.224}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_131.geometry}
            material={materials["Material.006"]}
            position={[2.354, 2.072, -4.699]}
            rotation={[2.032, -0.09, 2.505]}
            scale={0.09}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_133.geometry}
            material={materials["Material.006"]}
            position={[2.436, 1.993, -4.607]}
            rotation={[-0.018, 0.797, 0.7]}
            scale={0.048}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_135.geometry}
            material={materials["Material.006"]}
            position={[0.167, 1.352, 3.056]}
            rotation={[-1.766, 0.425, 1.256]}
            scale={0.441}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_137.geometry}
            material={materials["Material.006"]}
            position={[-0.285, 1.292, 3.197]}
            rotation={[2.032, -0.09, 2.505]}
            scale={0.177}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_139.geometry}
            material={materials["Material.006"]}
            position={[-0.055, 1.105, 3.367]}
            rotation={[3.133, 0.179, 2.926]}
            scale={0.094}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_141.geometry}
            material={materials["Material.004"]}
            position={[4.241, -2.38, 6.698]}
            rotation={[2.674, -0.429, 1.297]}
            scale={0.286}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_143.geometry}
            material={materials["Material.004"]}
            position={[3.892, -2.676, 6.936]}
            rotation={[-3.104, 0.521, -1.707]}
            scale={0.191}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model/scene.gltf");
